### ISSUE TITLE
collaborative notes

### ISSUE THREAD

**Issue by rasundsbak** [uio-carpentry/2022-11-24-uio#1]
hi, i would like to have two etherpads listed. One for each day. How should i separate the url:s?

etherpads
https://pad.carpentries.org/2022-11-25-blindern

and

https://pad.carpentries.org/2022-11-24-blindern

i tried this: 

[November 24th](https://pad.carpentries.org/2022-11-24-blindern)
[November 25th](https://pad.carpentries.org/2022-11-25-blindern)

the whole heading disappeared. Scary!
I have the 24th in. Want this listed:
collaborative_notes: https://pad.carpentries.org/2022-11-25-blindern

**Comment by arockenberger** [comment]
I apparently didn't see this issue. can be closed?
